browser:
  language: en  # Replace with your desired language code
  visible: false  # Set to true to show the browser window
  geolocation: US  # Replace with your country code
  proxy: ""  # Add your proxy here, e.g., "http://your-proxy:port"

url: "https://www.example.com"  # Replace with your desired URL
duration: 5  # Duration in minutes to visit the URL
