name: Run Browser Automation

on:
  workflow_dispatch:

jobs:
  run-automation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copy all files from root directory
        run: |
          mkdir -p /app
          cp -r * /app/

      - name: Make all files executable
        run: chmod -R 777 /app

      - name: Run Browser Automation Script
        run: /app/entryone.sh
