name: Run Browser Automation

on:
  workflow_dispatch:

jobs:
  run-automation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create app directory and copy files
        run: |
          mkdir -p $HOME/app
          cp -r $(pwd)/* $HOME/app/
          ls -al $HOME/app  # List files to verify copy

      - name: Make entryone.sh executable
        run: chmod -R 777 $HOME/app

      - name: Run Browser Automation Script
        run: $HOME/app/entryone.sh
