name: Run Browser Automation

on:
  workflow_dispatch:

jobs:
  run-automation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copy all files to runner's home directory
        run: |
          mkdir -p $HOME/app
          cp -r * $HOME/app/

      - name: Make entryone.sh executable
        run: chmod 777 $HOME/app/entryone.sh

      - name: Run Browser Automation Script
        run: $HOME/app/entryone.sh
