name: Run Browser Automation

on:
  workflow_dispatch:

jobs:
  run-automation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copy all files from root directory
        run: |
          mkdir -p /app
          cp -r * /app/

      - name: Make entryone.sh executable
        run: chmod +x /app/entryone.sh

      - name: Run Browser Automation Script
        run: /app/entryone.sh
