name: Run Browser Automation

on:
  workflow_dispatch:

jobs:
  run-automation:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      actions: write
    
    steps:
      - name: Debug Time
        run: date

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copy all files to runner's home directory
        run: |
          mkdir -p $HOME/app
          cp -r * $HOME/app/
          ls -al $HOME/app  # List files to verify copy

      - name: Make entryone.sh executable
        run: chmod +x $HOME/app/entryone.sh

      - name: Run Browser Automation Script
        run: |
          bash $HOME/app/entryone.sh
